"use client";

import { GitPullRequestArrow, MessageCircleQuestion } from "lucide-react";
import type { WhitepaperIssueCounts } from "@/lib/whitepapers";

const FEEDBACK_REPO_OWNER = "Nano-Collective";
const FEEDBACK_REPO_NAME = "docs";

/**
 * Mirrors Nextra's built-in feedback title format so the issue a reader
 * opens from this widget is indistinguishable from one opened from the
 * right-sidebar "Question? Give us feedback" link, and so the GitHub
 * search query below matches both interchangeably.
 *
 * Nextra's source: `getGitIssueUrl({ title: \`Feedback for "${pageTitle}"\` })`
 * where the quote characters are U+201C and U+201D.
 */
function buildTitlePrefix(title: string): string {
  return `Feedback for \u201C${title}\u201D`;
}

function buildIssueLink(title: string): string {
  const params = new URLSearchParams({
    title: buildTitlePrefix(title),
    body: "",
  });
  return `https://github.com/${FEEDBACK_REPO_OWNER}/${FEEDBACK_REPO_NAME}/issues/new?${params.toString()}`;
}

function buildIssueListLink(title: string, state: "open" | "closed"): string {
  // GitHub's web search uses the same query syntax as the API. We pass
  // the phrase as a quoted string to match exact substrings within the
  // title field, scoped to this repo. The web search page renders
  // `in:title` and `is:state` qualifiers correctly.
  const params = new URLSearchParams();
  params.set(
    "q",
    `repo:${FEEDBACK_REPO_OWNER}/${FEEDBACK_REPO_NAME} is:issue in:title "${buildTitlePrefix(title)}" is:${state}`,
  );
  return `https://github.com/${FEEDBACK_REPO_OWNER}/${FEEDBACK_REPO_NAME}/issues?${params.toString()}`;
}

/**
 * Inline feedback widget rendered in the page header (under the H1) on
 * whitepaper pages, alongside the proposer and status badges.
 *
 * Renders a "Question? Give us feedback" link that opens a pre-filled
 * GitHub issue titled `Feedback for "<title>"` (matching Nextra's
 * default format exactly), plus a count of open and closed issues for
 * the same whitepaper.
 *
 * Issue counts are server-rendered from `public/whitepapers.json`,
 * which is regenerated by the daily 00:15 UTC deploy workflow (see
 * `scripts/generate-whitepapers-manifest.ts`). No runtime fetch from
 * the browser — counts are baked into the static HTML and are at most
 * ~24h stale.
 */
export function WhitepaperFeedbackInline({
  title,
  issueCounts,
}: {
  title: string;
  issueCounts?: WhitepaperIssueCounts;
}) {
  const newIssueHref = buildIssueLink(title);
  const openListHref = buildIssueListLink(title, "open");
  const closedListHref = buildIssueListLink(title, "closed");

  return (
    <span className="not-prose inline-flex flex-wrap items-center gap-x-3 gap-y-1 text-sm">
      <a
        href={newIssueHref}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1.5 text-[var(--x-color-primary-600,#7aa2f7)] hover:underline"
      >
        <MessageCircleQuestion className="h-3.5 w-3.5" aria-hidden="true" />
        Question? Give us feedback.
      </a>

      {issueCounts && (
        <span className="inline-flex flex-wrap items-center gap-x-1.5 gap-y-0.5 text-[var(--x-color-fg-muted,#888)]">
          <GitPullRequestArrow className="h-3.5 w-3.5" aria-hidden="true" />
          {issueCounts.open > 0 ? (
            <a
              href={openListHref}
              target="_blank"
              rel="noopener noreferrer"
              className="underline decoration-dotted hover:text-[var(--x-color-fg,#000)] dark:hover:text-white"
            >
              {issueCounts.open} open
            </a>
          ) : (
            <span>0 open</span>
          )}
          {issueCounts.closed > 0 && (
            <>
              <span aria-hidden="true">·</span>
              <a
                href={closedListHref}
                target="_blank"
                rel="noopener noreferrer"
                className="underline decoration-dotted hover:text-[var(--x-color-fg,#000)] dark:hover:text-white"
              >
                {issueCounts.closed} closed
              </a>
            </>
          )}
          {issueCounts.total > 0 && (
            <>
              <span aria-hidden="true">·</span>
              <span>{issueCounts.total} total</span>
            </>
          )}
        </span>
      )}
    </span>
  );
}
