import fs from "node:fs";
import path from "node:path";

/**
 * Reader for the whitepaper manifest generated by
 * `scripts/generate-whitepapers-manifest.ts`. The manifest is rebuilt on
 * `prebuild` and committed to the repo, so this just reads from disk and
 * is safe to import from server components at build time.
 *
 * For the website (which consumes /whitepapers.json at build time over the
 * network), see website/lib/whitepapers.ts.
 */

export interface WhitepaperIssueCounts {
  open: number;
  closed: number;
  total: number;
}

export interface WhitepaperManifestEntry {
  slug: string;
  title: string;
  description: string;
  proposer?: string;
  proposer_github?: string;
  status?: string;
  review_opens?: string;
  review_closes?: string;
  sidebar_order?: number;
  issue_counts?: WhitepaperIssueCounts;
}

export interface WhitepaperManifest {
  generated_at: string;
  count: number;
  whitepapers: WhitepaperManifestEntry[];
}

const MANIFEST_PATH = path.join(process.cwd(), "public", "whitepapers.json");

let cached: WhitepaperManifest | null = null;

function readManifest(): WhitepaperManifest {
  if (cached) return cached;
  if (!fs.existsSync(MANIFEST_PATH)) {
    cached = { generated_at: "", count: 0, whitepapers: [] };
    return cached;
  }
  const raw = fs.readFileSync(MANIFEST_PATH, "utf-8");
  cached = JSON.parse(raw) as WhitepaperManifest;
  return cached;
}

export function getAllWhitepapers(): WhitepaperManifestEntry[] {
  return readManifest().whitepapers;
}

export function getWhitepaperBySlug(
  slug: string,
): WhitepaperManifestEntry | undefined {
  return readManifest().whitepapers.find((w) => w.slug === slug);
}

export function getWhitepaperIssueCounts(
  slug: string,
): WhitepaperIssueCounts | undefined {
  return getWhitepaperBySlug(slug)?.issue_counts;
}
